### ISSUE TITLE
pydegensac.findHomography() Modify

### ISSUE THREAD

**Issue by DoongLi** [ducha-aiki/pydegensac#20]
Hi, I want to modify the source code of pydegensac.findhomography (), such as modifying Ransac, so that the four pairs are distributed evenly. What should I do?

**Comment by ducha-aiki** [comment]
Modify the sampling process, which is called inside function `multirsampleT `
https://github.com/ducha-aiki/pydegensac/blob/master/src/pydegensac/degensac/rtools.c#L136

That being said, I would recommend you to do it in some more friendly-written repo, rather than here in low-level C.

Good candidate would be https://github.com/danini/graph-cut-ransac/

**Comment by DoongLi** [comment]
Thanks for your advice！I will try.
